global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']  # Monitor Prometheus itself
  - job_name: 'node_exporter'      # Optional: Add if using node-exporter
    static_configs:
      - targets: ['<node-exporter-host>:9100']